### ISSUE TITLE
Operating Speed

### ISSUE THREAD

**Issue by mohanjiao** [ibgp2/ibgp2#2]
After I add some more nodes, the running time becomes very long.
Is there any way to speed up the operation? For example, remove unnecessary output, or reduce the switching time interval

**Comment by ibgp2** [comment]
Hello,

Unfortunately, your issue is due to ns3, and this is why I advise you to run simulations on small topologies. You could do is to increase the OSPF intervals, hence less packets will be exchanged and the simulation should be faster. In `example/dce-ibgpv2-simu.cc` update `SetupOspfInterface` to decrease those delays :

```cpp
    std::string name = OspfConfig::MakeInterfaceName ( i );
    OspfInterface ospfInterface ( name, weight );
    ospfInterface.SetHelloInterval ( 2 );
    ospfInterface.SetDeadInterval ( 3 * ospfInterface.GetHelloInterval() );
    ospfInterface.SetTransmitDelay ( 1 );
    ospfInterface.SetRetransmitInterval ( 3 );
    ospfConfig->AddInterface ( ospfInterface );
```

... but this is "normal" values for a core network, and increasing them while slow the IGP convergence...

Best regards

**Comment by mohanjiao** [comment]
I'm sorry to bother you again after a long time

I've tried what you said, but it's not obvious

I see part of ospf-config.cc

// interface ... (and ip ospf ...)

os << "router ospf " << std::endl;

os << " timers throttle spf 100 100 1000" << std::endl;

Can I change the SPF algorithm running frequency in OSPF Protocol?

Maybe we can speed up the algorithm by increasing the calculation interval, but I can't find where to modify it

Can you tell me where to modify it?

**Comment by mohanjiao** [comment]
By the way, do you try to run in parallel?

For example, using MPI

**Comment by ibgp2** [comment]
I'm not sure to understand what you want to do with MPI.

- If you are talking about the simulator, and assuming you want to run say 4 simulations in parallel because you have 4 CPU, then just open 4 terminals and run one simulation per terminal.
- If you are talking about iBGP2, the current code do not use MPI and is not parallelized. Some parts of iBGP2 could be parallelized. Locally to iBGP2 router, this router updates iBGP routing policy when the IGP topology changes. iBGP2 computes its on a per iBGP-peer basis. So you could parallelize these computations.

**Comment by mohanjiao** [comment]
i mean ns3-dce and quagga
It's very difficult to parallelize

**Comment by ibgp2** [comment]
Probably. You should contact people involved in ns3-dce if you have idea to improve this.
